### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by ogxd** [dr-dotnet/dr-dotnet#70]
# Requirements

- Static webpage (eg zola?)
- Git versioned
- Markdown format
- Schematics as code
  - Mermaid.js compatible https://gist.github.com/mtolk/7b24e452f9b0e197d63ced900e087ff9
- Cover all RELEASE current profilers
  - CPU sampled profiler
  - Merged stacks profiler
  - ...
- Version in header ?
- URL ?
  - `ogxd.github.io/drdotnet`
  - `drdotnet.github.io` is taken
  - `dr-dotnet.github.io` does not match [hub.docker.com/r/drdotnet](https://hub.docker.com/r/drdotnet)

**Comment by szarykott** [comment]
If I may, as I have used Zola for my personal blog, you might want to check [Hugo](https://gohugo.io/), which seems to have a bigger user base and more themes. Or at least this was the case last time I checked.

**Comment by ogxd** [comment]
I picked Zola because I wanted to reuse the theme and the GitHub action I've made for this project https://github.com/ogxd/ffidji. AdiDoks for Zola was looking quite nice https://github.com/aaranxu/adidoks, but it does not seems really maintained so I might switch to Hugo at some point if we encounter issues. Thanks for the information!
